### ISSUE TITLE
Replacement rules for GO terms

### ISSUE THREAD

**Issue by rankishore** [valearna/genedesc_generator#5]
Replacements for GO terms:
1. GO: 'molting cycle, collagen and cuticulin-based cuticle', with 'molting cycle' 
2. GO: 'molting cycle, chitin-based cuticle' with 'molting cycle'.
3. GO:  term 'multicellular organism growth' with 'growth'.
4. GO:  'embryo development ending in birth or egg hatching' with 'embryo development'
5. GO:  'synaptic transmission, \<text string\>' with '\<text string\> synaptic transmission'.

**Comment by valearna** [comment]
Can these rules be applied to all organisms in AGR?
