### ISSUE TITLE
WS291 automated descriptions ace file has a bug

### ISSUE THREAD

**Issue by rankishore** [valearna/genedesc_generator#64]
@valearna In testing my upload files in acedb on the textpresso-labs.com new system, acedb complains about the file 20230901_automatedesc.ace (autoamated descriptions .ace file for WS291). Looks like when we added the "Paper_evidence" tag, two things happened:
1. An empty line got introduced for every gene before the "Paper-evidence" line.  So now acedb is complaining about the class "Automated_description".  We need to remove this empty line for every gene and then test again. I am sure this is a simple bug to fix and this is what acedb is complaining about.
2. We lost the space between the next gene
 
Should be an easy fix, I am sure acedb is complaining about these, as now the syntax/format is messed up.

**Comment by valearna** [comment]
Thanks @rankishore I'll fix this asap!

**Comment by valearna** [comment]
fixed the bug and restarted the pipeline. New GDs will be ready by the en of the day

**Comment by rankishore** [comment]
The new automated descriptions .ace files (09/11) passed testing without any error messages on acedb on the new textpresso-labs.com system. I think we are good to go. Thanks
