### ISSUE TITLE
Move Human function module in C. elegans WB descriptions after the orthology sentence.

### ISSUE THREAD

**Issue by valearna** [valearna/genedesc_generator#65]
Move human function description in elegans gene descriptions after the orthology sentence in order to improve readability and avoid confusion.

Current description:

WB:WBGene00000065	act-3
Expressed in gonad and head. Human ortholog(s) of this gene implicated in several diseases, including Baraitser-Winter syndrome 1; Baraitser-Winter syndrome 2; and autosomal dominant nonsyndromic deafness 20. Human ACTB Contributes to nucleosomal DNA binding activity. Human ACTB enables several functions, including Tat protein binding activity; enzyme binding activity; and kinesin binding activity. A structural constituent of postsynaptic actin cytoskeleton. Is predicted to encode a protein with the following domains: Actin family; Phosphorylation site; ATPase, nucleotide binding domain; and Actin. Is an ortholog of human ACTB (actin beta).

What it should be:
Expressed in gonad and head. Human ortholog(s) of this gene implicated in several diseases, including Baraitser-Winter syndrome 1; Baraitser-Winter syndrome 2; and autosomal dominant nonsyndromic deafness 20. A structural constituent of postsynaptic actin cytoskeleton. Is predicted to encode a protein with the following domains: Actin family; Phosphorylation site; ATPase, nucleotide binding domain; and Actin. Is an ortholog of human ACTB (actin beta). Human ACTB Contributes to nucleosomal DNA binding activity. Human ACTB enables several functions, including Tat protein binding activity; enzyme binding activity; and kinesin binding activity.

**Comment by rankishore** [comment]
I can see that the human function sentence (either "enables" or "contributes") has been moved to the end of the description, so this issue has been resolved.
