### ISSUE TITLE
Remove capitalization from "Contributes to" in human functional sentences in C. elegans

### ISSUE THREAD

**Issue by valearna** [valearna/genedesc_generator#66]
Human ACTB Contributes to nucleosomal DNA binding activity. Human ACTB enables several functions, including Tat protein binding activity; enzyme binding activity; and kinesin binding activity. 

"Contributes to" should be lowercase

**Comment by rankishore** [comment]
Issue resolved, now I can see, for example, gene act -3 has "contributes" in the human gene function statement.
